Repository pyro-ppl/pyro-api, pull requests merged in 2019-10, with the labels that each got.

#1 Seed repo with pyro.generic
  .travis.yml
  pyroapi/__init__.py
  pyroapi/dispatch.py
  pyroapi/testing.py
  pyroapi/version.py
  setup.py
  test/test_dispatch.py
Labels: awaiting review

#4 Add setup.cfg and flake8 state to ci
  .travis.yml
  setup.cfg
  test/test_dispatch.py
Labels: awaiting review

#3 Add pyroapi.tests module with example usage
  pyroapi/tests.py
  test/conftest.py
  test/test_tests.py
Labels: awaiting review, discussion

#7 Switch funsor backend to use funsor.compat.ops
  pyroapi/dispatch.py
  setup.py
Labels: awaiting review, easy

#5 Add simple svi tests to pyroapi.tests
  .travis.yml
  pyroapi/tests.py
  pyroapi/tests/__init__.py
  pyroapi/tests/test_svi.py
  test/test_tests.py
Labels: awaiting review, discussion

#8 Minor fixes to make code backend agnostic
  .gitignore
  pyroapi/tests/test_svi.py
Labels: awaiting review

#10 Add sphinx docs
  Makefile
  docs/Makefile
  docs/make.bat
  docs/source/conf.py
  docs/source/dispatch.rst
  docs/source/index.rst
  docs/source/testing.rst
  setup.py
Labels: awaiting review, documentation

#11 Add register_backend() function
  docs/source/dispatch.rst
  pyroapi/__init__.py
  pyroapi/dispatch.py
  test/test_dispatch.py
Labels: awaiting review

#12 Add badges to readme
  README.md
Labels: easy

#13 Add license, code of conduct, release instructions
  CODE_OF_CONDUCT.md
  LICENSE.md
  setup.py
Labels: awaiting review

#14 Bump to version 0.1.1 for release
  pyroapi/dispatch.py
  pyroapi/version.py
  test/test_dispatch.py
  test/test_tests.py
Labels: awaiting review
